# Generated by Django 5.1.3 on 2024-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link_to_video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
