# Generated by Django 5.1.3 on 2024-11-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_description_alter_lesson_link_to_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='lms/preview/course', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='lms/preview/lesson', verbose_name='Превью'),
        ),
    ]
